root: true
extends:
- "@sethb0/mfllc"
- "plugin:vue/recommended"
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2019
  ecmaFeatures:
    jsx: false
  sourceType: module
plugins:
- babel
- promise
- vue
env:
  es6: true
  browser: true
globals:
  process: false
rules:
  object-curly-newline:
  - warn
  - ObjectExpression:
      consistent: true
      multiline: true
      minProperties: 4
    ObjectPattern: never
    ImportDeclaration: never
    ExportDeclaration: never
  require-await: off

  vue/html-indent:
  - warn
  - 2
  - alignAttributesVertically: false
  vue/html-self-closing:
  - warn
  - html:
      void: never
      normal: never
      component: never
    svg: always
    math: always
  vue/max-attributes-per-line: off
  vue/no-unused-components: warn
  vue/no-unused-vars: warn
  vue/return-in-computed-property: warn
  vue/singleline-html-element-content-newline: off

  promise/always-return: warn
  promise/catch-or-return: warn
  promise/no-nesting: warn

  new-cap: off
  babel/new-cap: warn
  no-invalid-this: off
  babel/no-invalid-this: warn
  object-curly-spacing: off
  babel/object-curly-spacing:
  - warn
  - always
  quotes: off
  babel/quotes:
  - warn
  - single
  - avoidEscape: true
  semi: off
  babel/semi: error
  no-unused-expressions: off
  babel/no-unused-expressions: warn
  valid-typeof: off
  babel/valid-typeof: warn
overrides:
- files: ["run.js", "*.config.js", "server/**", "initdb/**", "bot/**"]
  env:
    browser: false
    node: true
- files: "*.config.js"
  rules:
    no-process-env: off
- files: "**/*.spec.js"
  env:
    mocha: true
  rules:
    func-names: off
    babel/no-invalid-this: off
    babel/no-unused-expressions: off
    prefer-arrow-callback: off
