root: true
extends:
- "@sethb0/mfllc-vue"
env:
  browser: true
globals:
  process: false
overrides:
- files: ["run.js", "*.config.js", "server/**", "bot/**"]
  env:
    browser: false
    node: true
- files: "*.config.js"
  rules:
    no-process-env: off
